# Generated by Django 2.1.3 on 2018-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('quantity_total', models.IntegerField(default=0)),
                ('price_unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('state', models.IntegerField()),
                ('price_total', models.IntegerField(default=0)),
                ('datesale', models.DateField()),
                ('order_description', models.CharField(max_length=64)),
            ],
        ),
    ]
