# Generated by Django 2.1.3 on 2018-11-15 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertickets',
            old_name='datesale',
            new_name='date_create',
        ),
        migrations.AddField(
            model_name='ordertickets',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 15, 1, 17, 34, 98788, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
