# Generated by Django 2.1.3 on 2018-11-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181115_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('is_host', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ConcertTickets',
            new_name='EventFeatures',
        ),
    ]
