# Generated by Django 2.1.3 on 2018-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181115_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertickets',
            name='date_create',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ordertickets',
            name='exp_date',
            field=models.DateField(max_length=64),
        ),
    ]
